---
title: "Welcome to My Blog"
description: |
  Welcome to our new blog, My Blog, this blog primarily concerning machine learning, text as data, and networks.
author:
  - name: Noah Milstein 
    url: {}
    affiliation: UMASS DACSS
    affiliation_url: https://www.umass.edu/sbs/data-analytics-and-computational-social-science-program/people/students
date: 03-29-2022
output:
  distill::distill_article:
    self_contained: false
---

```{r,include=FALSE}
library(aRtsy)
```

```{r, include=FALSE}
library(ggChernoff)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

```{r, include=FALSE}
library(ggplot2)
```

```{r}
?aRtsy
```

```{r}
set.seed(30)

canvas_maze(color = colorPalette("tuscany2"), polar = TRUE)

```

```{r}
?canvas_flow()
set.seed(1)
canvas_flow(colors = colorPalette("vrolik3"), lines = 3000, lwd = 0.5,
            iterations = 1000, stepmax = 0.1, angles = NULL)
# see ?canvas_flow for more input parameters of this function
```

```{r}
set.seed(1)
canvas_flow(colors = colorPalette("vrolik3"), lines = 3000, lwd = 0.5,
            iterations = 1000, stepmax = 0.1, angles = 'svm')
# see ?canvas_flow for more input parameters of this function
```



```{r, include=FALSE}
?chernoffGrob
face <- chernoffGrob(.5, .5, size = 1e3, smile = 1, colour = 'black', fill = 'yellow')
grid::grid.newpage()
grid::grid.draw(face)
```

