---
title: "Brining it All Together (Extended Networks Towards Thesis"
description: |
  Here I extend my inital networks from 1000-1300 to the year 1900.
author:
  - name: Noah Milstein
    url: {}
date: 2022-05-03
output:
  distill::distill_article:
    self_contained: false
---
```{r}
library(readxl)
library(igraph)
library(statnet)
library(network)
library(tidyverse)
library(ggnetwork)
library(GGally)
library(ggplot2)
library(sna)
library(intergraph)
library(ggbiplot)
library(knitr)
library(GGally)
library(aRtsy)
library(stringr)

```


```{r setup, include=FALSE}

wars_in_1000s <- read_excel("~/Desktop/Spring 2022/Networks/wars_in_1000s.xlsx")

wars_in_1000s$"Out-list" <- sapply(wars_in_1000s$"Out-list",
                                    function(x) { gsub("[\r\n]", "", x) })
wars_in_1000s$"In-list"<- sapply(wars_in_1000s$"In-list",
                                    function(x) { gsub("[\r\n]", "", x) })

wars_in_1100s <- read_excel("~/Desktop/Spring 2022/Networks/wars_in_1100s.xlsx")

wars_in_1100s$"Out" <- sapply(wars_in_1100s$"Out",
                                    function(x) { gsub("[\r\n]", "", x) })
wars_in_1100s$"In"<- sapply(wars_in_1100s$"In",
                                    function(x) { gsub("[\r\n]", "", x) })

wars_in_1200s <- read_excel("~/Desktop/Spring 2022/Networks/wars_in_1200s.xlsx")


wars_in_1200s$"Out" <- sapply(wars_in_1200s$"Out",
                                    function(x) { gsub("[\r\n]", "", x) })

wars_in_1200s$"In"<- sapply(wars_in_1200s$"In",  
                                    function(x) { gsub("[\r\n]", "", x) })

wars_in_1300s <- read_excel("~/Desktop/Spring 2022/Networks/wars_in_1300s.xlsx")

wars_in_1300s$"In" <- sapply(wars_in_1300s$"Out-List",
                                    function(x) { gsub("[\r\n]", "", x) })
wars_in_1300s$"Out"<- sapply(wars_in_1300s$"In-List",  
                                    function(x) { gsub("[\r\n]", "", x) })

wars_in_1300s <- wars_in_1300s[,c(6:7)]
# Had non-breaking spaces so I had to use str_trim()
wars_in_1300s$In <- str_trim(wars_in_1300s$In)

wars_in_1300s$Out <- str_trim(wars_in_1300s$Out)

wars_in_1400s <- read_excel("~/Desktop/Spring 2022/Networks/wars_in_1400s.xlsx")

wars_in_1400s$"In" <- sapply(wars_in_1400s$"In-List",
                                    function(x) { gsub("[\r\n]", "", x) })
wars_in_1400s$"Out"<- sapply(wars_in_1400s$"Out-List",  
                                    function(x) { gsub("[\r\n]", "", x) })

wars_in_1400s <- wars_in_1400s[,c(6:7)]

wars_in_1400s$In <- str_trim(wars_in_1400s$In)

wars_in_1400s$Out <- str_trim(wars_in_1400s$Out)

wars_in_1500s <- read_excel("~/Desktop/Spring 2022/Networks/wars_in_1500s.xlsx")

wars_in_1500s$"In" <- sapply(wars_in_1500s$"In-List",
                                    function(x) { gsub("[\r\n]", "", x) })
wars_in_1500s$"Out"<- sapply(wars_in_1500s$"Out-List",  
                                    function(x) { gsub("[\r\n]", "", x) })

wars_in_1500s <- wars_in_1500s[,c(6:7)]

wars_in_1500s$In <- str_trim(wars_in_1500s$In)

wars_in_1500s$Out <- str_trim(wars_in_1500s$Out)

wars_in_1600s <- read_excel("~/Desktop/Spring 2022/Networks/wars_in_1600s.xlsx")

wars_in_1600s$"In" <- sapply(wars_in_1600s$"In-List",
                                    function(x) { gsub("[\r\n]", "", x) })
wars_in_1600s$"Out"<- sapply(wars_in_1600s$"Out-List",  
                                    function(x) { gsub("[\r\n]", "", x) })

wars_in_1600s <- wars_in_1600s[,c(6:7)]

wars_in_1600s$In <- str_trim(wars_in_1600s$In)

wars_in_1600s$Out <- str_trim(wars_in_1600s$Out)

wars_in_1700s <- read_excel("~/Desktop/Spring 2022/Networks/wars_in_1700s.xlsx")

wars_in_1700s$"In" <- sapply(wars_in_1700s$"In-List",
                                    function(x) { gsub("[\r\n]", "", x) })
wars_in_1700s$"Out"<- sapply(wars_in_1700s$"Out-List",  
                                    function(x) { gsub("[\r\n]", "", x) })

wars_in_1700s <- wars_in_1700s[,c(6:7)]

wars_in_1700s$In <- str_trim(wars_in_1700s$In)

wars_in_1700s$Out <- str_trim(wars_in_1700s$Out)

wars_in_1800s <- read_excel("~/Desktop/Spring 2022/Networks/wars_in_1800s.xlsx")

wars_in_1800s$In <- sapply(wars_in_1800s$"In-List",
                                    function(x) { gsub("[\r\n]", "", x) })
wars_in_1800s$Out<- sapply(wars_in_1800s$"Out-List",  
                                    function(x) { gsub("[\r\n]", "", x) })

wars_in_1800s <- wars_in_1800s[,c(6:7)]

wars_in_1800s$In <- str_trim(wars_in_1800s$In)

wars_in_1800s$Out <- str_trim(wars_in_1800s$Out)

```

```{r}

wars_in_1000s_edgelist <- as.matrix(wars_in_1000s)

wars_in_1000s_edgelist_network_edgelist <- graph.edgelist(wars_in_1000s_edgelist, directed=TRUE)

wars_in_1000s.ig<-graph_from_data_frame(wars_in_1000s)

wars_in_1000s_network <- asNetwork(wars_in_1000s.ig)

wars_1000s<-as.matrix(as_adjacency_matrix(wars_in_1000s.ig))

wars_in_1100s_edgelist <- as.matrix(wars_in_1100s)

wars_in_1100s_edgelist_network_edgelist <- graph.edgelist(wars_in_1100s_edgelist, directed=TRUE)

wars_in_1100s.ig<-graph_from_data_frame(wars_in_1100s)

wars_in_1100s_network <- asNetwork(wars_in_1100s.ig)

wars_1100s<-as.matrix(as_adjacency_matrix(wars_in_1100s.ig))

wars_in_1200s_edgelist <- as.matrix(wars_in_1200s)

wars_in_1200s_edgelist_network_edgelist <- graph.edgelist(wars_in_1200s_edgelist, directed=TRUE)

wars_in_1200s.ig<-graph_from_data_frame(wars_in_1200s)

wars_in_1200s_network <- asNetwork(wars_in_1200s.ig)

wars_1200s<-as.matrix(as_adjacency_matrix(wars_in_1200s.ig))

wars_in_1300s_edgelist <- as.matrix(wars_in_1300s)

wars_in_1300s_edgelist_network_edgelist <- graph.edgelist(wars_in_1300s_edgelist, directed=TRUE)

wars_in_1300s.ig<-graph_from_data_frame(wars_in_1300s)

wars_in_1300s_network <- asNetwork(wars_in_1300s.ig)

wars_1300s<-as.matrix(as_adjacency_matrix(wars_in_1300s.ig))

wars_in_1400s_edgelist <- as.matrix(wars_in_1400s)

wars_in_1400s_edgelist_network_edgelist <- graph.edgelist(wars_in_1400s_edgelist, directed=TRUE)

wars_in_1400s.ig<-graph_from_data_frame(wars_in_1400s)

wars_in_1400s_network <- asNetwork(wars_in_1400s.ig)

wars_1400s<-as.matrix(as_adjacency_matrix(wars_in_1400s.ig))

wars_in_1500s_edgelist <- as.matrix(wars_in_1500s)

wars_in_1500s_edgelist_network_edgelist <- graph.edgelist(wars_in_1500s_edgelist, directed=TRUE)

wars_in_1500s.ig<-graph_from_data_frame(wars_in_1500s)

wars_in_1500s_network <- asNetwork(wars_in_1500s.ig)

wars_1500s<-as.matrix(as_adjacency_matrix(wars_in_1500s.ig))

wars_in_1600s_edgelist <- as.matrix(wars_in_1600s)

wars_in_1600s_edgelist_network_edgelist <- graph.edgelist(wars_in_1600s_edgelist, directed=TRUE)

wars_in_1600s.ig<-graph_from_data_frame(wars_in_1600s)

wars_in_1600s_network <- asNetwork(wars_in_1600s.ig)

wars_1600s<-as.matrix(as_adjacency_matrix(wars_in_1600s.ig))

wars_in_1700s_edgelist <- as.matrix(wars_in_1700s)

wars_in_1700s_edgelist_network_edgelist <- graph.edgelist(wars_in_1700s_edgelist, directed=TRUE)

wars_in_1700s.ig<-graph_from_data_frame(wars_in_1700s)

wars_in_1700s_network <- asNetwork(wars_in_1700s.ig)

wars_1700s<-as.matrix(as_adjacency_matrix(wars_in_1700s.ig))

wars_in_1800s_edgelist <- as.matrix(wars_in_1800s)

wars_in_1800s_edgelist_network_edgelist <- graph.edgelist(wars_in_1800s_edgelist, directed=TRUE)

wars_in_1800s.ig<-graph_from_data_frame(wars_in_1800s)

wars_in_1800s_network <- asNetwork(wars_in_1800s.ig)

wars_1800s<-as.matrix(as_adjacency_matrix(wars_in_1800s.ig))

```

```{r}
summary(wars_in_1000s_network)
summary(wars_in_1100s_network)
summary(wars_in_1200s_network)


```

```{r}

set.seed(777)
ggplot(wars_in_1000s_network, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "grey25", alpha = 0.25, arrow = arrow(length = unit(2, "pt"), type = "closed"))+
  geom_nodes(color = "purple1", alpha = 0.3, size = 2) +
  geom_nodetext(aes( label = vertex.names ), size=1)+
    ggtitle("Networks of Wars in the 1000s") +
  theme_blank()
```

```{r}

set.seed(777)
ggplot(wars_in_1100s_network, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "grey25", alpha = 0.25, arrow = arrow(length = unit(2, "pt"), type = "closed"))+
  geom_nodes(color = "gold", alpha = 0.3, size = 2) +
  geom_nodetext(aes( label = vertex.names ), size=1)+
    ggtitle("Networks of Wars in the 1100s") +
  theme_blank()
```

```{r}

set.seed(777)
ggplot(wars_in_1200s_network, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "grey25", alpha = 0.25, arrow = arrow(length = unit(2, "pt"), type = "closed"))+
  geom_nodes(color = "forestgreen", alpha = 0.3, size = 2) +
  geom_nodetext(aes( label = vertex.names ), size=1)+
    ggtitle("Networks of Wars in the 1200s") +
  theme_blank()
```

```{r}

set.seed(777)
ggplot(wars_in_1300s_network, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "grey25", alpha = 0.25, arrow = arrow(length = unit(2, "pt"), type = "closed"))+
  geom_nodes(color = "burlywood1", alpha = 0.3, size = 2) +
  geom_nodetext(aes( label = vertex.names ), size=1)+
    ggtitle("Networks of Wars in the 1300s") +
  theme_blank()
```

```{r}

set.seed(777)
ggplot(wars_in_1400s_network, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "grey25", alpha = 0.25, arrow = arrow(length = unit(2, "pt"), type = "closed"))+
  geom_nodes(color = "aquamarine2", alpha = 0.3, size = 2) +
  geom_nodetext(aes( label = vertex.names ), size=1)+
    ggtitle("Networks of Wars in the 1400s") +
  theme_blank()
```

```{r}

set.seed(777)
ggplot(wars_in_1500s_network, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "grey25", alpha = 0.25, arrow = arrow(length = unit(2, "pt"), type = "closed"))+
  geom_nodes(color = "mediumorchid1", alpha = 0.3, size = 2) +
  geom_nodetext(aes( label = vertex.names ), size=1)+
    ggtitle("Networks of Wars in the 1500s") +
  theme_blank()
```

```{r}

set.seed(777)
ggplot(wars_in_1600s_network, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "grey25", alpha = 0.25, arrow = arrow(length = unit(2, "pt"), type = "closed"))+
  geom_nodes(color = "plum2", alpha = 0.3, size = 2) +
  geom_nodetext(aes( label = vertex.names ), size=1)+
    ggtitle("Networks of Wars in the 1600s") +
  theme_blank()
```

```{r}

set.seed(777)
ggplot(wars_in_1700s_network, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "grey25", alpha = 0.25, arrow = arrow(length = unit(2, "pt"), type = "closed"))+
  geom_nodes(color = "tomato1", alpha = 0.3, size = 2) +
  geom_nodetext(aes( label = vertex.names ), size=1)+
    ggtitle("Networks of Wars in the 1700s") +
  theme_blank()
```

```{r}

set.seed(777)
ggplot(wars_in_1800s_network, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "grey25", alpha = 0.25, arrow = arrow(length = unit(2, "pt"), type = "closed"))+
  geom_nodes(color = "steelblue1", alpha = 0.3, size = 2) +
  geom_nodetext(aes( label = vertex.names ), size=1)+
    ggtitle("Networks of Wars in the 1800s") +
  theme_blank()
```

```{r}

set.seed(238)
#Run clustering algorithm: fast_greedy
wars_in_1000s.wt<-walktrap.community(wars_in_1000s.ig)

#igraph::groups(wars_in_1000s.wt)

```

Adding more steps resulted in 19 groups for both 10 and 20 steps.

```{r}
#Run & inspect clustering algorithm: 10 steps
#igraph::groups(walktrap.community(wars_in_1000s.ig, steps=10)) 
#Run & inspect clustering algorithm: 20 steps
#igraph::groups(walktrap.community(wars_in_1000s.ig ,steps=20))
#Run & inspect clustering algorithm
```

```{r, echo=FALSE}

plot(wars_in_1000s.wt, wars_in_1000s.ig, vertex.size=0.5, edge.size=0.25, edge.arrow.size=.25,  vertex.label.dist=1.5,vertex.label.cex=0.25,asp = 0)

```
```{r}

set.seed(238)
#Run clustering algorithm: fast_greedy
wars_in_1100s.wt<-walktrap.community(wars_in_1100s.ig)

#igraph::groups(wars_in_1000s.wt)

```

```{r, echo=FALSE}

plot(wars_in_1100s.wt, wars_in_1100s.ig, vertex.size=0.5, edge.size=0.25, edge.arrow.size=.25,  vertex.label.dist=1.5,vertex.label.cex=0.25,asp = 0)

```

```{r}

set.seed(238)
#Run clustering algorithm: fast_greedy
wars_in_1200s.wt<-walktrap.community(wars_in_1200s.ig)

#igraph::groups(wars_in_1000s.wt)

```

```{r, echo=FALSE}

plot(wars_in_1200s.wt, wars_in_1200s.ig, vertex.size=0.5, edge.size=0.25, edge.arrow.size=.25,  vertex.label.dist=1.5,vertex.label.cex=0.25,asp = 0)

```

```{r}

set.seed(238)
#Run clustering algorithm: fast_greedy
wars_in_1300s.wt<-walktrap.community(wars_in_1300s.ig)

#igraph::groups(wars_in_1000s.wt)

```

```{r, echo=FALSE}

plot(wars_in_1300s.wt, wars_in_1300s.ig, vertex.size=0.5, edge.size=0.25, edge.arrow.size=.25,  vertex.label.dist=1.5,vertex.label.cex=0.25,asp = 0)

```

```{r}

set.seed(238)
#Run clustering algorithm: fast_greedy
wars_in_1400s.wt<-walktrap.community(wars_in_1400s.ig)

#igraph::groups(wars_in_1000s.wt)

```

```{r, echo=FALSE}

plot(wars_in_1400s.wt, wars_in_1400s.ig, vertex.size=0.5, edge.size=0.25, edge.arrow.size=.25,  vertex.label.dist=1.5,vertex.label.cex=0.25,asp = 0)

```

```{r}

set.seed(238)
#Run clustering algorithm: fast_greedy
wars_in_1500s.wt<-walktrap.community(wars_in_1500s.ig)

#igraph::groups(wars_in_1000s.wt)

```

```{r, echo=FALSE}

plot(wars_in_1500s.wt, wars_in_1500s.ig, vertex.size=0.5, edge.size=0.25, edge.arrow.size=.25,  vertex.label.dist=1.5,vertex.label.cex=0.25,asp = 0)

```
```{r}

set.seed(238)
#Run clustering algorithm: fast_greedy
wars_in_1600s.wt<-walktrap.community(wars_in_1600s.ig)

#igraph::groups(wars_in_1000s.wt)

```

```{r, echo=FALSE}

plot(wars_in_1600s.wt, wars_in_1600s.ig, vertex.size=0.5, edge.size=0.25, edge.arrow.size=.25,  vertex.label.dist=1.5,vertex.label.cex=0.25,asp = 0)

```

```{r}

set.seed(238)
#Run clustering algorithm: fast_greedy
wars_in_1700s.wt<-walktrap.community(wars_in_1700s.ig)

#igraph::groups(wars_in_1000s.wt)

```

```{r, echo=FALSE}

plot(wars_in_1700s.wt, wars_in_1700s.ig, vertex.size=0.5, edge.size=0.25, edge.arrow.size=.25,  vertex.label.dist=1.5,vertex.label.cex=0.25,asp = 0)

```

```{r}

set.seed(238)
#Run clustering algorithm: fast_greedy
wars_in_1800s.wt<-walktrap.community(wars_in_1800s.ig)

#igraph::groups(wars_in_1000s.wt)

```

```{r, echo=FALSE}

plot(wars_in_1800s.wt, wars_in_1800s.ig, vertex.size=0.5, edge.size=0.25, edge.arrow.size=.25,  vertex.label.dist=1.5,vertex.label.cex=0.25,asp = 0)

```

```{r}
library(ape)
library(ggdendro)
library(sets)
library(ggplot2)
library(dendextend)
library(RColorBrewer)

```

```{r}

#pdf("h_clust_plot.pdf") 

dd <- dist(scale(wars_1000s), method = "euclidean")

hc <- hclust(dd, method = "complete")

dend <- hc %>% as.dendrogram() %>%
   set("branches_k_color", k=39) %>% 
  set("branches_lwd", 1)  %>%     
  set("labels_cex", c(.3,0.3)) 

# plot the dend in usual "base" plotting engine:
plot(dend,col="white", type="rectangle", frame.plot = FALSE, center	=FALSE, xlab="Belligerents", ylab="Distance (Euclidean)", main="Complete, Euclidean Distance Dendrogram" , cex=0.5,   horiz = FALSE)



```

```{r}

#pdf("h_clust_plot.pdf") 

dd <- dist(scale(wars_1100s), method = "euclidean")

hc <- hclust(dd, method = "complete")

dend <- hc %>% as.dendrogram() %>%
   set("branches_k_color", k=39) %>% 
  set("branches_lwd", 1)  %>%     
  set("labels_cex", c(.2,0.2)) 

# plot the dend in usual "base" plotting engine:
plot(dend,col="white", type="rectangle", frame.plot = FALSE, center	=FALSE, xlab="Belligerents", ylab="Distance (Euclidean)", main="Complete, Euclidean Distance Dendrogram" , cex=0.5,   horiz = FALSE)



```

```{r}

#pdf("h_clust_plot.pdf") 

dd <- dist(scale(wars_1200s), method = "euclidean")

hc <- hclust(dd, method = "complete")

dend <- hc %>% as.dendrogram() %>%
   set("branches_k_color", k=39) %>% 
  set("branches_lwd", 1)  %>%     
  set("labels_cex", c(.2,0.2)) 

# plot the dend in usual "base" plotting engine:
plot(dend,col="white", type="rectangle", frame.plot = FALSE, center	=FALSE, xlab="Belligerents", ylab="Distance (Euclidean)", main="Complete, Euclidean Distance Dendrogram" , cex=0.5,   horiz = FALSE)



```

```{r}

#pdf("h_clust_plot.pdf") 

dd <- dist(scale(wars_1300s), method = "euclidean")

hc <- hclust(dd, method = "complete")

dend <- hc %>% as.dendrogram() %>%
   set("branches_k_color", k=39) %>% 
  set("branches_lwd", 1)  %>%     
  set("labels_cex", c(.2,0.2)) 

# plot the dend in usual "base" plotting engine:
plot(dend,col="white", type="rectangle", frame.plot = FALSE, center	=FALSE, xlab="Belligerents", ylab="Distance (Euclidean)", main="Complete, Euclidean Distance Dendrogram" , cex=0.5,   horiz = FALSE)

```

```{r}

#pdf("h_clust_plot.pdf") 

dd <- dist(scale(wars_1400s), method = "euclidean")

hc <- hclust(dd, method = "complete")

dend <- hc %>% as.dendrogram() %>%
   set("branches_k_color", k=39) %>% 
  set("branches_lwd", 1)  %>%     
  set("labels_cex", c(.15,0.15)) 

# plot the dend in usual "base" plotting engine:
plot(dend,col="white", type="rectangle", frame.plot = FALSE, center	=FALSE, xlab="Belligerents", ylab="Distance (Euclidean)", main="Complete, Euclidean Distance Dendrogram" , cex=0.5,   horiz = FALSE)

```

```{r}

#pdf("h_clust_plot.pdf") 

dd <- dist(scale(wars_1500s), method = "euclidean")

hc <- hclust(dd, method = "complete")

dend <- hc %>% as.dendrogram() %>%
   set("branches_k_color", k=39) %>% 
  set("branches_lwd", 1)  %>%     
  set("labels_cex", c(.15,0.15)) 

# plot the dend in usual "base" plotting engine:
plot(dend,col="white", type="rectangle", frame.plot = FALSE, center	=FALSE, xlab="Belligerents", ylab="Distance (Euclidean)", main="Complete, Euclidean Distance Dendrogram" , cex=0.5,   horiz = FALSE)

```

```{r}

#pdf("h_clust_plot.pdf") 

dd <- dist(scale(wars_1600s), method = "euclidean")

hc <- hclust(dd, method = "complete")

dend <- hc %>% as.dendrogram() %>%
   set("branches_k_color", k=39) %>% 
  set("branches_lwd", 1)  %>%     
  set("labels_cex", c(.15,0.15)) 

# plot the dend in usual "base" plotting engine:
plot(dend,col="white", type="rectangle", frame.plot = FALSE, center	=FALSE, xlab="Belligerents", ylab="Distance (Euclidean)", main="Complete, Euclidean Distance Dendrogram" , cex=0.5,   horiz = FALSE)

```

```{r}

#pdf("h_clust_plot.pdf") 

dd <- dist(scale(wars_1700s), method = "euclidean")

hc <- hclust(dd, method = "complete")

dend <- hc %>% as.dendrogram() %>%
   set("branches_k_color", k=39) %>% 
  set("branches_lwd", 1)  %>%     
  set("labels_cex", c(.15,0.15)) 

# plot the dend in usual "base" plotting engine:
plot(dend,col="white", type="rectangle", frame.plot = FALSE, center	=FALSE, xlab="Belligerents", ylab="Distance (Euclidean)", main="Complete, Euclidean Distance Dendrogram" , cex=0.5,   horiz = FALSE)

```

```{r}

#pdf("h_clust_plot.pdf") 

set.seed(883)

dd <- dist(scale(wars_1800s), method = "euclidean")

hc <- hclust(dd, method = "complete")

dend <- hc %>% as.dendrogram() %>%
   set("branches_k_color", k=39) %>% 
  set("branches_lwd", 1)  %>%     
  set("labels_cex", c(.1,0.1)) 

# plot the dend in usual "base" plotting engine:
plot(dend,col="white", type="rectangle", frame.plot = FALSE, center	=FALSE, xlab="Belligerents", ylab="Distance (Euclidean)", main="Complete, Euclidean Distance Dendrogram" , cex=0.5,   horiz = FALSE)

```

## Trade Data

```{r}
library('maps')
library('geosphere')
library(diagram)
library(plotrix)
```

```{r, warning=FALSE}

#pdf("1800_map.pdf") 
set.seed(15887) 
aspects_of_1800s_states_for_map <- read_excel("~/Desktop/Spring 2022/Networks/aspects_of_1800s_states_for_map.xlsx")

aspects_of_1800s_states_for_map <- aspects_of_1800s_states_for_map[,c(1:3)]

cl <- colors(distinct = TRUE)

# to set random generator seed

mycols2 <- sample(cl, 502)
mycols3 <- sample(cl, 145)
mycols2<-c(mycols2, mycols3)
palette(mycols2)

map('world', fill = TRUE, col = "white", mar = rep(0, 4), resolution = 10 , myborder = 0.001, bg="skyblue1") 

nodes <- transform(aspects_of_1800s_states_for_map, countries = as.factor(aspects_of_1800s_states_for_map$name))

with(nodes, points(long, Lat, col=countries, pch=19, cex=0.5)) 

edges <- subset(data.frame(from = wars_in_1800s$In, to = wars_in_1800s$Out, stringsAsFactors = F), from != to)

edges <- merge(merge(edges, nodes[, c("name", "long", "Lat")], by.x = "from", by.y = "name"), nodes[, c("name", "long", "Lat")], by.x = "to", by.y = "name")

edges$col <- as.integer(nodes$countries[match(edges$from, nodes$name)])

edges$long.x<-as.integer(edges$long.x)

edges$Lat.x<-as.integer(edges$Lat.x)

edges$long.y<-as.integer(edges$long.y)

edges$Lat.y<-as.integer(edges$Lat.y)

apply(edges[,-(1:2)], 1, function(x)
curvedarrow(to=x[3:4], from=x[1:2], lcol=x[5], 
            curve=.1, arr.pos = 1, lwd=.2, arr.lwd=0.01, 
                          arr.width=0.1, arr.length=0.1))
```


